# /Users/ven/.config/nix/nix-darwin/darwin/modules/services/docker/nginx.nix
#
# NGINX: CUSTOM SERVICE (NO services.nginx)
# ========================================
# - Installs nginx from Nixpkgs.
# - Writes a main nginx.conf to:
#       $HOME/ven-dots/conf/nginx.conf
# - Includes per-app configs from:
#       $HOME/ven-dots/conf/apps-enabled/*.conf
# - Creates a launchd daemon on macOS.
# - Creates a systemd service on Linux.
# ========================================

{ config, pkgs, lib, ... }:

let
  isDarwin = pkgs.stdenv.isDarwin;
  isLinux  = pkgs.stdenv.isLinux;

  userHome = config.users.users.ven.home;

  confRoot   = "${userHome}/ven-dots/conf";
  nginxConf  = "${confRoot}/nginx.conf";
  appsDir    = "${confRoot}/apps-enabled";
  logsDir    = "${confRoot}/logs";

  nginxBin   = "${pkgs.nginx}/bin/nginx";

  mainConfig = ''
    # AUTO-GENERATED BY NIX
    # Do not edit this file by hand; change it via nginx.nix instead.

    worker_processes  1;

    events {
      worker_connections 1024;
    }

    http {
      include       mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  ${logsDir}/access.log  main;
      error_log   ${logsDir}/error.log;

      sendfile        on;
      keepalive_timeout  65;

      # Per-app configs
      include ${appsDir}/*.conf;
    }
  '';

  runner = pkgs.writeShellScriptBin "run-nginx-custom" ''
    #!/usr/bin/env bash
    set -euo pipefail

    echo ">>> [nginx] Using config: ${nginxConf}"

    # Test config before starting
    "${nginxBin}" -t -c "${nginxConf}"

    echo ">>> [nginx] Starting nginx (daemon off)"
    exec "${nginxBin}" -g "daemon off;" -c "${nginxConf}"
  '';
in
{
  # Install nginx system-wide
  environment.systemPackages = [ pkgs.nginx ];

  # Ensure directories + main config exist
  system.activationScripts.nginx-setup.text = lib.mkAfter ''
    echo ">>> [nginx] Setting up nginx directories and config"

    mkdir -p "${confRoot}"
    mkdir -p "${appsDir}"
    mkdir -p "${logsDir}"

    echo ">>> [nginx] Writing main nginx.conf to ${nginxConf}"
    cat > "${nginxConf}" <<'EOF'
${mainConfig}
EOF
  '';

  # macOS: launchd service
  launchd.daemons.nginx-custom = lib.mkIf isDarwin {
    serviceConfig = {
      Label           = "com.ven.nginx-custom";
      ProgramArguments = [ "${runner}/bin/run-nginx-custom" ];
      RunAtLoad       = true;
      KeepAlive       = true;
      WorkingDirectory = "${confRoot}";
    };
  };

  # Linux: systemd service
  systemd.services.nginx-custom = lib.mkIf isLinux {
    description = "Custom nginx (Nix-managed)";
    wantedBy    = [ "multi-user.target" ];
    serviceConfig = {
      Type      = "simple";
      ExecStart = "${runner}/bin/run-nginx-custom";
      Restart   = "always";
      WorkingDirectory = "${confRoot}";
    };
  };
}
