# /Users/ven/.config/nix/nix-darwin/darwin/modules/services/docker/nginx.nix
#
# NGINX: CUSTOM SERVICE (DARWIN ONLY)
# ===================================
# - Installs nginx from Nixpkgs
# - Writes main nginx.conf to:
#       $HOME/ven-dots/conf/nginx.conf
# - Loads per-app configs from:
#       $HOME/ven-dots/conf/apps-enabled/*.conf
# - Creates launchd daemon to run nginx with that config
# ===================================

{ config, pkgs, lib, ... }:

let
  userHome = config.users.users.ven.home;

  confRoot   = "${userHome}/ven-dots/conf";
  nginxConf  = "${confRoot}/nginx.conf";
  appsDir    = "${confRoot}/apps-enabled";
  logsDir    = "${confRoot}/logs";

  nginxBin   = "${pkgs.nginx}/bin/nginx";

  mainConfig = ''
    # AUTO-GENERATED BY NIX
    # Do not edit this file by hand; change it via nginx.nix instead.

    worker_processes  1;

    events {
      worker_connections 1024;
    }

    http {
      include       mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  ${logsDir}/access.log  main;
      error_log   ${logsDir}/error.log;

      sendfile        on;
      keepalive_timeout  65;

      include ${appsDir}/*.conf;
    }
  '';

  nginxSetupScript = pkgs.writeShellScriptBin "nginx-setup" ''
    #!/usr/bin/env bash
    set -euo pipefail

    echo ">>> [nginx] Setting up nginx directories and config"

    mkdir -p "${confRoot}"
    mkdir -p "${appsDir}"
    mkdir -p "${logsDir}"

    echo ">>> [nginx] Writing main nginx.conf to ${nginxConf}"
    cat > "${nginxConf}" <<'EOF'
${mainConfig}
EOF
  '';

  runner = pkgs.writeShellScriptBin "run-nginx-custom" ''
    #!/usr/bin/env bash
    set -euo pipefail

    echo ">>> [nginx] Using config: ${nginxConf}"

    "${nginxBin}" -t -c "${nginxConf}"

    echo ">>> [nginx] Starting nginx (daemon off)"
    exec "${nginxBin}" -g "daemon off;" -c "${nginxConf}"
  '';
in
{
  # Install nginx binary
  environment.systemPackages = [ pkgs.nginx ];

  # Activation: prepare config + dirs
  system.activationScripts.nginx-setup.text = lib.mkAfter ''
    "${nginxSetupScript}/bin/nginx-setup"
  '';

  # launchd: start nginx using custom config
  launchd.daemons.nginx-custom = {
    serviceConfig = {
      Label           = "com.ven.nginx-custom";
      ProgramArguments = [ "${runner}/bin/run-nginx-custom" ];
      RunAtLoad       = true;
      KeepAlive       = true;
      WorkingDirectory = "${confRoot}";
    };
  };
}
