# /Users/ven/.config/nix/nix-darwin/darwin/modules/services/docker/nginx.nix
#
# NGINX (DARWIN)
# ============================================================
# - Installs nginx from Nixpkgs.
# - Writes a main nginx.conf to:
#       ~/ven-dots/conf/nginx.conf
# - Includes virtual hosts from:
#       ~/ven-dots/conf/apps-enabled/*.conf
# - Logs to:
#       ~/ven-dots/conf/logs/{access,error}.log
# - Provides a run-nginx-custom wrapper.
# - Creates a launchd daemon:
#       com.ven.nginx-custom
# ============================================================

{ config, pkgs, lib, ... }:

let
  userHome = config.users.users.ven.home;

  confRoot   = "${userHome}/ven-dots/conf";
  nginxConf  = "${confRoot}/nginx.conf";
  appsDir    = "${confRoot}/apps-enabled";
  logsDir    = "${confRoot}/logs";

  nginxBin   = "${pkgs.nginx}/bin/nginx";

  mainConfig = ''
    # AUTO-GENERATED BY NIX - DO NOT EDIT BY HAND
    pid ${confRoot}/nginx.pid;
    error_log ${logsDir}/error.log;

    worker_processes  1;

    events {
      worker_connections 1024;
    }

    http {
      # Use nginx's own mime.types from Nix store
      include       ${pkgs.nginx}/conf/mime.types;
      default_type  application/octet-stream;

      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      access_log  ${logsDir}/access.log  main;
      error_log   ${logsDir}/error.log;

      sendfile        on;
      keepalive_timeout  65;

      # Per-app configs (Vaultwarden etc.)
      include ${appsDir}/*.conf;
    }
  '';

  nginxSetupScript = pkgs.writeShellScriptBin "nginx-setup" ''
    #!/usr/bin/env bash
    set -euo pipefail

    echo ">>> [nginx] Creating config + folders"
    echo ">>> [nginx]   conf: ${confRoot}"
    echo ">>> [nginx]   apps: ${appsDir}"
    echo ">>> [nginx]   logs: ${logsDir}"

    mkdir -p "${confRoot}" "${appsDir}" "${logsDir}"
    touch "${logsDir}/access.log" "${logsDir}/error.log"

    echo ">>> [nginx] Writing nginx.conf → ${nginxConf}"
    cat > "${nginxConf}" <<'EOF'
${mainConfig}
EOF
  '';

  runner = pkgs.writeShellScriptBin "run-nginx-custom" ''
    #!/usr/bin/env bash
    set -euo pipefail

    echo ">>> [nginx] Starting nginx with ${nginxConf}"

    # Test config before starting
    "${nginxBin}" -t -c "${nginxConf}" || {
      echo "!!! [nginx] nginx -t FAILED for ${nginxConf}"
      exit 78
    }

    echo ">>> [nginx] nginx -t OK, launching (daemon off)"
    exec "${nginxBin}" \
      -e "/Users/ven/ven-dots/conf/logs/error.log" \
      -g "daemon off;" \
      -c "${nginxConf}"
  '';
in
{
  # Install nginx and helper scripts
  environment.systemPackages = [ pkgs.nginx nginxSetupScript runner ];

  # Stable wrapper path for launchd (avoids /nix/store path churn)
  environment.etc."ven/services/run-nginx-custom".source =
    "${runner}/bin/run-nginx-custom";

  # Ensure folders + nginx.conf exist at activation
  system.activationScripts.extraActivation.text = lib.mkAfter ''
    echo ">>> Running nginx-setup"
    ${nginxSetupScript}/bin/nginx-setup || echo "!!! nginx-setup failed (continuing)"
  '';

  # Launchd daemon: com.ven.nginx-custom
  launchd.daemons.nginx-custom = {
    serviceConfig = {
      Label            = "com.ven.nginx-custom";
      ProgramArguments = [ "/etc/ven/services/run-nginx-custom" ];
      RunAtLoad        = true;
      KeepAlive = {
          Crashed = true;
          SuccessfulExit = false;
        };
        ThrottleInterval = 10;
      WorkingDirectory = "${confRoot}";
    };
  };
}
