# shared/home/pkgs-configs/espanso/base.nix
#
# =====================================================================
# ESPANSO: BASE MATCHES
#
# Owns Espanso's default text-expansion match file:
#
#   ~/.config/espanso/match/base.yml
#
# Nix owns the contents of this file. Home Manager creates the normal
# Espanso path as a symlink to the immutable Nix-store file generated
# from the text declared below.
# =====================================================================

{ paths }:

{ config, lib, ... }:

let
  cfg = config.ven.espanso;
in
{
  home.file.${paths.relative.espanso.baseMatches} = lib.mkIf (cfg.enable && cfg.base.enable) {
    text = ''
      # This file is generated by Nix. Edit the shared Espanso module.
      matches: []
    '';
  };
}
