# shared/home/pkgs-configs/espanso/default.nix
#
# =====================================================================
# ESPANSO
#
# Selects Espanso's shared configuration features and owns the Nix-owned
# config/default.yml file.
#
# Its sibling modules own match/base.yml and match/markdown.yml. Package
# installation and app linking remain in shared/packages.nix.
# =====================================================================

{ paths }:

{ config, lib, ... }:

let
  cfg = config.ven.espanso;
in
{
  # ------------------------------------------------------------
  # ------ ESPANSO CONFIGURATION FILE MODULES ------ #
  # This module owns default.yml and imports the Espanso match-file owners.

  imports = [
    (import ./base.nix { inherit paths; })
    (import ./markdown.nix { inherit paths; })
  ];

  config = {
    # ------------------------------------------------------------
    # ------ SHARED ESPANSO FEATURE SELECTION ------ #
    # Shared chooses which declared Espanso features are applied.

    ven.espanso = {
      enable = true;
      showNotifications = true;

      base.enable = true;

      markdown = {
        enable = true;

        links = {
          enable = true;

          standard = {
            enable = true;
            trigger = ":mdlink";
            title = "Title";
            link = "Link";
          };

          obsidian = {
            enable = true;
            trigger = ":wikilink";
            text = "Text";
          };

          obsidianAlias = {
            enable = false;
            trigger = ":wikialias";
            link = "Link";
            title = "Title";
          };

          autolink = {
            enable = false;
            trigger = ":mdurl";
            link = "Link";
          };

          image = {
            enable = false;
            trigger = ":mdimage";
            alt = "Alt text";
            link = "Image URL";
          };
        };

        formatting = {
          enable = true;

          bold = {
            enable = true;
            trigger = ":mdbold";
            text = "Text";
          };

          task = {
            enable = true;
            trigger = ":mdtask";
          };
        };
      };
    };

    # ------------------------------------------------------------
    # ------ ESPANSO DEFAULT CONFIGURATION ------ #
    # Home Manager owns the symlink to this immutable Nix-generated file.

    home.file.${paths.relative.espanso.defaultConfig} = lib.mkIf cfg.enable {
      text = ''
        # This file is generated by Nix. Edit the shared Espanso module.
        show_notifications: ${if cfg.showNotifications then "true" else "false"}
      '';
    };
  };
}
