# darwin/services/docker/nginx.nix
#
# =====================================================================
# NGINX
# 
# - Installs nginx from Nixpkgs.
# - Writes a main nginx.conf to:
#       ~/.config/conf/nginx.conf
# - Includes virtual hosts from:
#       ~/.config/conf/apps-enabled/*.conf
# - Logs to:
#       ~/.config/conf/logs/{access,error}.log
# - Provides a run-nginx-custom wrapper.
# - Creates a launchd daemon:
#       com.ven.nginx-custom
# =====================================================================

{ config, pkgs, lib, ... }:

let
# ------------------------------------------------------- # 
# ------ USER VARIABLES ------ #
# ------------------------------------------------------- # 
  userHome = config.users.users.ven.home;

  confRoot   = "${userHome}/.config/nginx/";
  nginxConf  = "${confRoot}/nginx.conf";
  appsDir    = "${confRoot}/apps-enabled";
  logsDir    = "${confRoot}/logs";

  nginxBin   = "${pkgs.nginx}/bin/nginx";
  # ------------------------------------------------------- # 

  
  # ------------------------------------------------------- # 
  # ------ MAIN NGINX CONFIG (nginx.conf) ------ #
  mainConfig = ''
    # AUTO-GENERATED BY NIX - DO NOT EDIT BY HAND
    pid ${confRoot}/nginx.pid;
    error_log ${logsDir}/error.log;

    # ** Worker process means the number of worker processes that Nginx will spawn to handle incoming requests
    # ** The optimal number of worker processes depends on the number of CPU cores available on the system and the expected traffic load.
	# ** For a low-traffic environment, 1 worker process is sufficient. For a high-traffic environment, you may want to increase the number of worker processes to match the number of CPU cores available on the system.
    worker_processes  1;

    # ** Worker connections means the maximum number of simultaneous connections that each worker process can handle.
	# ** The optimal number of worker connections depends on the expected traffic load and the available system resources. For a low-traffic environment, 1024 worker connections is sufficient. For a high-traffic environment, you may want to increase the number of worker connections to handle more simultaneous connections.
    events {
      worker_connections 1024;
    }

    # ** The http block is the main configuration block for the HTTP server in Nginx. It contains directives that apply to all HTTP requests and responses, such as logging, MIME types, and connection settings.

    # ------------------------------------------------------- # 
    # ------ SET HTTP SERVER CONFIGURATION ------ #
    # Set up the HTTP server with logging, MIME types, and connection settings
    http {
      # Use nginx's own mime.types from Nix store
      include       ${pkgs.nginx}/conf/mime.types;

      # Set the default MIME type for files that do not have a specific MIME type defined
      default_type  application/octet-stream;

      # Set up logging format for access logs
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      # Set up access and error logs
      access_log  ${logsDir}/access.log  main;
      error_log   ${logsDir}/error.log;

      # Set up connection settings for keep-alive and timeouts
      sendfile        on;
      keepalive_timeout  65;

      # Per-app configs (Vaultwarden etc.)
      include ${appsDir}/*.conf;
    }
  '';
  # ------------------------------------------------------- # 

  nginxSetupScript = pkgs.writeShellScriptBin "nginx-setup" ''
    #!/usr/bin/env bash
    set -euo pipefail

    # Print messages for debugging
    echo ">>> [nginx] Creating config + folders"
    echo ">>> [nginx]   conf: ${confRoot}"
    echo ">>> [nginx]   apps: ${appsDir}"
    echo ">>> [nginx]   logs: ${logsDir}"

    # Ensure config + folders exist
    mkdir -p "${confRoot}" "${appsDir}" "${logsDir}"
    touch "${logsDir}/access.log" "${logsDir}/error.log"

    # Write main nginx.conf
    echo ">>> [nginx] Writing nginx.conf → ${nginxConf}"
    cat > "${nginxConf}" <<'EOF'
${mainConfig}
EOF
  '';
  # Runner script to start nginx with the custom config
  runner = pkgs.writeShellScriptBin "run-nginx-custom" ''
    #!/usr/bin/env bash
    set -euo pipefail

    echo ">>> [nginx] Starting nginx with ${nginxConf}"

    # Test config before starting
    "${nginxBin}" -t -c "${nginxConf}" || {
      echo "!!! [nginx] nginx -t FAILED for ${nginxConf}"
      
      # ** exit 78 means "configuration error" in nginx's exit codes
      exit 78
    }

    # Launch nginx with the custom config in the foreground (daemon off)
    echo ">>> [nginx] nginx -t OK, launching (daemon off)"
    exec "${nginxBin}" \

      # error log path
      -e "/Users/ven/.config/nginx/logs/error.log" \

      # Global directives applying to the entire Nginx server, the location of the PID file, and the error log path 
      -g "daemon off;" \

      # Specify the path to the main configuration file (nginx.conf)
      -c "${nginxConf}"
  '';
in
{
  # Install nginx and helper scripts
  environment.systemPackages = [ pkgs.nginx nginxSetupScript runner ];

  # Stable wrapper path for launchd (avoids /nix/store path churn)
  environment.etc."ven/services/run-nginx-custom".source =

  	# Stable wrapper path for launchd (avoids /nix/store path churn)
    "${runner}/bin/run-nginx-custom";

  # Ensure folders + nginx.conf exist at activation
  system.activationScripts.extraActivation.text = lib.mkAfter ''
    echo ">>> Running nginx-setup"
    
    # Run the nginx-setup script to create the necessary directories and write the main nginx.conf
    ${nginxSetupScript}/bin/nginx-setup || echo "!!! nginx-setup failed (continuing)"
  '';

  # Launchd daemon: com.ven.nginx-custom
  launchd.agents.nginx-custom = {
    serviceConfig = {

      # Stable label for the launchd daemon
      # ** 'label' is a unique identifier for the launchd job, used to manage and control the service.
      Label            = "com.ven.nginx-custom";

      # Specify the command and its arguments to run the service
      ProgramArguments = [ "/etc/ven/services/run-nginx-custom" ];

      # Run the service when the system loads
      RunAtLoad        = true;

      # Keep the service alive; if it exits, launchd will restart it
      KeepAlive        = true;

      # Set the working directory for the service to the configuration root
      WorkingDirectory = "${confRoot}";
    };
  };
}
