# darwin/services/docker/nginx.nix
#
# =====================================================================
# NGINX
#
# - Installs nginx from Nixpkgs.
# - Generates the main config into the Nix store and links it to:
#       /etc/nginx/nginx.conf
# - Generates one file per registered virtual host and links them to:
#       /etc/nginx/apps-enabled/<name>.conf
# - Logs to:
#       /var/log/nginx/{access,error}.log
# - Writes its pid to:
#       /var/run/nginx-custom.pid
# - Provides run-nginx-custom and nginx-custom-reload wrappers.
# - Creates a launchd daemon for privileged HTTP(S) ports:
#       com.ven.nginx-custom
#
# Another module registers a virtual host with:
#
#     ven.nginx.virtualHosts.<name> = '' ... '';
#
# The daemon plist deliberately contains no generated content. A config
# change therefore never makes launchd unload and reload nginx, which is
# what previously released ports 80/443 mid-activation. Changes reach the
# running master through a graceful reload instead, which keeps the
# listening sockets bound.
# =====================================================================

{ config, pkgs, lib, ... }:

let
  cfg = config.ven.nginx;

  # Shared path roots (/etc, /var/log, /var/run, /etc/ven/services).
  paths = import ../../../options/paths.nix { };
  systemPaths = paths.darwin.system;

  # ------------------------------------------------------- #
  # ------ PATHS ------ #
  # Config is store-backed and reached through /etc symlinks.
  # Runtime state must stay writable, so it lives outside the store.
  # ------------------------------------------------------- #
  confRoot  = "${systemPaths.etc}/${cfg.etcDir}";
  nginxConf = "${confRoot}/nginx.conf";
  appsDir   = "${confRoot}/apps-enabled";

  nginxBin = "${pkgs.nginx}/bin/nginx";

  # Coreutils are addressed absolutely: launchd and activation both run
  # with a minimal PATH that must not be relied on.
  mkdirBin = "${pkgs.coreutils}/bin/mkdir";
  catBin   = "${pkgs.coreutils}/bin/cat";

  # Generation-stable wrapper path used by the launchd daemon.
  runnerName   = "run-nginx-custom";
  runnerTarget = "${systemPaths.venServicesTarget}/${runnerName}";
  runnerPath   = "${systemPaths.venServices}/${runnerName}";
  # ------------------------------------------------------- #


  # ------------------------------------------------------- #
  # ------ VIRTUAL HOST INCLUDES ------ #
  # One explicit include per registered vhost.
  #
  # ** A '*.conf' glob was used before. An explicit list is safer: a file
  # ** left behind in apps-enabled can never be picked up by accident,
  # ** and nginx fails loudly when a declared vhost is missing instead of
  # ** starting with a silently incomplete configuration.
  vhostIncludes =
    lib.concatMapStringsSep "\n      "
      (name: "include ${appsDir}/${name}.conf;")
      (lib.attrNames cfg.virtualHosts);
  # ------------------------------------------------------- #


  # ------------------------------------------------------- #
  # ------ MAIN NGINX CONFIG (nginx.conf) ------ #
  mainConfig = ''
    # AUTO-GENERATED BY NIX - DO NOT EDIT BY HAND
    # Source: darwin/services/docker/nginx.nix
    pid ${cfg.pidFile};
    error_log ${cfg.logDir}/error.log;

    # Run request workers as the normal user after the root master binds ports.
    user ${cfg.user} ${cfg.group};

    # ** Worker process means the number of worker processes that Nginx will spawn to handle incoming requests
    # ** The optimal number of worker processes depends on the number of CPU cores available on the system and the expected traffic load.
	# ** For a low-traffic environment, 1 worker process is sufficient. For a high-traffic environment, you may want to increase the number of worker processes to match the number of CPU cores available on the system.
    worker_processes  ${toString cfg.workerProcesses};

    # ** Worker connections means the maximum number of simultaneous connections that each worker process can handle.
	# ** The optimal number of worker connections depends on the expected traffic load and the available system resources. For a low-traffic environment, 1024 worker connections is sufficient. For a high-traffic environment, you may want to increase the number of worker connections to handle more simultaneous connections.
    events {
      worker_connections ${toString cfg.workerConnections};
    }

    # ** The http block is the main configuration block for the HTTP server in Nginx. It contains directives that apply to all HTTP requests and responses, such as logging, MIME types, and connection settings.

    # ------------------------------------------------------- #
    # ------ SET HTTP SERVER CONFIGURATION ------ #
    # Set up the HTTP server with logging, MIME types, and connection settings
    http {
      # Use nginx's own mime.types from Nix store
      include       ${pkgs.nginx}/conf/mime.types;

      # Set the default MIME type for files that do not have a specific MIME type defined
      default_type  application/octet-stream;

      # Set up logging format for access logs
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      # Set up access and error logs
      access_log  ${cfg.logDir}/access.log  main;
      error_log   ${cfg.logDir}/error.log;

      # Set up connection settings for keep-alive and timeouts
      sendfile        on;
      keepalive_timeout  ${toString cfg.keepaliveTimeout};

      # Per-app configs (Vaultwarden etc.), registered via ven.nginx.virtualHosts
      ${vhostIncludes}
    }
  '';
  # ------------------------------------------------------- #


  # ------------------------------------------------------- #
  # ------ RUNNER (foreground service supervised by launchd) ------ #
  runner = pkgs.writeShellScriptBin "run-nginx-custom" ''
    set -euo pipefail

    echo ">>> [nginx] Starting nginx with ${nginxConf}"

    # The log directory holds runtime state and is never store-backed,
    # so make sure it exists before nginx tries to open its log files.
    "${mkdirBin}" -p "${cfg.logDir}"

    # Test config before starting
    "${nginxBin}" -t -c "${nginxConf}" || {
      echo "!!! [nginx] nginx -t FAILED for ${nginxConf}"

      # ** exit 78 means "configuration error" in nginx's exit codes
      exit 78
    }

    # Launch nginx with the custom config in the foreground (daemon off).
    # Keep arguments together: comments inside a continued shell command
    # would make Bash ignore the remaining Nginx arguments.
    echo ">>> [nginx] nginx -t OK, launching (daemon off)"
    exec "${nginxBin}" -e "${cfg.logDir}/error.log" -g "daemon off;" -c "${nginxConf}"
  '';
  # ------------------------------------------------------- #


  # ------------------------------------------------------- #
  # ------ GRACEFUL RELOAD (run from activation) ------ #
  #
  # ** 'nginx -s reload' sends SIGHUP to the running master. The master
  # ** keeps its listening sockets, starts workers with the new config and
  # ** retires the old ones. Ports 80/443 are never released, so nothing
  # ** else can take them and proxied services do not drop connections.
  #
  # This script never starts and never kills nginx. Starting is launchd's
  # job; killing was the old manual repair that this design avoids.
  #
  # ** It is deliberately silent on success. A rebuild should not scroll
  # ** past routine nginx chatter, so output means something needs looking
  # ** at. Startup logging belongs in the runner below, which writes to
  # ** /var/log/com.ven.nginx-custom.out.log instead of the terminal.
  reloader = pkgs.writeShellScriptBin "nginx-custom-reload" ''
    set -euo pipefail

    LOG_PREFIX="[nginx-reload]"

    # The config is a symlink into the Nix store created by environment.etc.
    if [ ! -e "${nginxConf}" ]; then
      echo "!!! $LOG_PREFIX ${nginxConf} is missing; nothing to reload"
      exit 0
    fi

    # Validate quietly. nginx's own "syntax is ok" chatter is captured and
    # only printed when it actually rejects the configuration.
    if ! test_output="$("${nginxBin}" -t -c "${nginxConf}" 2>&1)"; then
      echo "!!! $LOG_PREFIX config is INVALID; NOT reloading"
      echo "$test_output"
      echo "!!! $LOG_PREFIX the running nginx was left untouched"
      exit 1
    fi

    # No pid file means nginx is not running, which is normal here:
    # launchd owns starting it. Nothing worth reporting.
    if [ ! -f "${cfg.pidFile}" ]; then
      exit 0
    fi

    nginx_pid="$("${catBin}" "${cfg.pidFile}" 2>/dev/null || true)"

    # A stale pid file is reported, never repaired automatically.
    if [ -z "$nginx_pid" ] || ! kill -0 "$nginx_pid" 2>/dev/null; then
      echo "!!! $LOG_PREFIX stale pid file at ${cfg.pidFile}"
      echo "!!! $LOG_PREFIX not reloading, and not killing anything"
      echo "!!! $LOG_PREFIX manual repair: sudo launchctl kickstart -k system/${cfg.label}"
      exit 0
    fi

    # Reload quietly. Only a failed reload is worth interrupting a rebuild.
    if ! reload_output="$("${nginxBin}" -s reload -e "${cfg.logDir}/error.log" -c "${nginxConf}" 2>&1)"; then
      echo "!!! $LOG_PREFIX reload FAILED for master pid $nginx_pid"
      echo "$reload_output"
      exit 1
    fi
  '';
  # ------------------------------------------------------- #


  # ------------------------------------------------------- #
  # ------ GENERATED /etc ENTRIES ------ #
  # environment.etc targets are relative to /etc. Each entry becomes
  # /etc/<target> -> /etc/static/<target> -> /nix/store/...
  #
  # nix-darwin removes /etc links whose store target disappears, so a
  # vhost removed from ven.nginx.virtualHosts also loses its file.
  etcEntries =
    {
      "${cfg.etcDir}/nginx.conf".text = mainConfig;
    }
    // lib.mapAttrs'
      (name: text:
        lib.nameValuePair "${cfg.etcDir}/apps-enabled/${name}.conf" { inherit text; })
      cfg.virtualHosts;
  # ------------------------------------------------------- #
in
{
  # =====================================================================
  # OPTIONS
  # =====================================================================
  options.ven.nginx = {
    enable = lib.mkEnableOption "the custom nginx reverse proxy";

    # ---- CONFIG LOCATION
    etcDir = lib.mkOption {
      type = lib.types.str;
      default = "nginx";

      # Relative to /etc, because environment.etc targets are relative.
      description = "Directory below /etc holding the generated nginx configuration.";
    };

    # ---- RUNTIME STATE
    logDir = lib.mkOption {
      type = lib.types.str;
      default = "${systemPaths.logs}/nginx";
      description = "Directory for nginx access and error logs.";
    };

    pidFile = lib.mkOption {
      type = lib.types.str;
      default = "${systemPaths.run}/nginx-custom.pid";
      description = "Pid file written by the nginx master process.";
    };

    # ---- PROCESS IDENTITY
    user = lib.mkOption {
      type = lib.types.str;
      default = "ven";
      description = "User that nginx worker processes run as.";
    };

    group = lib.mkOption {
      type = lib.types.str;
      default = "staff";
      description = "Group that nginx worker processes run as.";
    };

    label = lib.mkOption {
      type = lib.types.str;
      default = "com.ven.nginx-custom";

      # ** Renaming this strands the old plist in /Library/LaunchDaemons,
      # ** where launchd keeps loading it at every boot while nix-darwin no
      # ** longer manages it. That is what previously left an old nginx
      # ** holding port 80. Treat this value as frozen.
      description = "launchd Label for the nginx daemon. Do not rename.";
    };

    # ---- TUNING
    workerProcesses = lib.mkOption {
      type = lib.types.int;
      default = 1;
      description = "Number of nginx worker processes.";
    };

    workerConnections = lib.mkOption {
      type = lib.types.int;
      default = 1024;
      description = "Maximum simultaneous connections per worker process.";
    };

    keepaliveTimeout = lib.mkOption {
      type = lib.types.int;
      default = 65;
      description = "Keep-alive timeout in seconds.";
    };

    # ---- VIRTUAL HOSTS
    virtualHosts = lib.mkOption {
      type = lib.types.attrsOf lib.types.lines;
      default = { };

      # Each entry becomes /etc/nginx/apps-enabled/<name>.conf and gets an
      # explicit include line in nginx.conf.
      example = lib.literalExpression ''
        { vaultwarden = "server { listen 443 ssl; }"; }
      '';
      description = "Virtual host configurations included by the main nginx config.";
    };
  };

  # =====================================================================
  # IMPLEMENTATION
  # =====================================================================
  config = lib.mkIf cfg.enable {

    # Install nginx and helper scripts
    environment.systemPackages = [ pkgs.nginx runner reloader ];

    # Generated configuration, linked into /etc from the Nix store.
    environment.etc = etcEntries // {

      # Stable wrapper path for launchd (avoids /nix/store path churn)
      "${runnerTarget}".source = "${runner}/bin/${runnerName}";
    };

    # Create the log directory only. The configuration itself is handled
    # by the etc activation step, which runs later than this one.
    # Silent unless the directory cannot be created.
    system.activationScripts.extraActivation.text = lib.mkAfter ''
      "${mkdirBin}" -p "${cfg.logDir}" || echo "!!! [nginx] could not create ${cfg.logDir} (continuing)"
    '';

    # Apply configuration changes to the already running nginx.
    #
    # ** nix-darwin runs its activation steps in this order:
    # **   extraActivation -> etc -> launchd -> postActivation
    # ** The reload must therefore run in postActivation: only by then have
    # ** the /etc symlinks been updated to the new generation.
    #
    # ** The '|| echo' is required, not cosmetic: the activation script runs
    # ** under 'set -e', so an unhandled non-zero exit here would abort the
    # ** whole switch. nginx never gets to break a rebuild.
    system.activationScripts.postActivation.text = lib.mkAfter ''
      ${reloader}/bin/nginx-custom-reload || echo "!!! [nginx] reload step failed (continuing)"
    '';

    # Launchd daemon: com.ven.nginx-custom
    # Nginx needs a root master process to bind ports 80 and 443.
    #
    # ** Nothing generated appears in this plist, so it stays byte-identical
    # ** across rebuilds and nix-darwin never unloads the daemon.
    launchd.daemons.nginx-custom = {
      serviceConfig = {

        # Stable label for the launchd daemon
        # ** 'label' is a unique identifier for the launchd job, used to manage and control the service.
        Label            = cfg.label;

        # Start through macOS' built-in Bash. The system LaunchDaemon may run
        # before /nix, /etc/ven, or the generated nginx config are ready
        # after boot.
        ProgramArguments = [
          "/bin/bash"
          "-c"
          ''
            set -u

            echo ">>> [nginx-launchd] Waiting for nginx files after boot"

            while true; do
              if [ -x "${runnerPath}" ] && [ -e "${nginxConf}" ]; then
                echo ">>> [nginx-launchd] Required paths are ready"
                exec "${runnerPath}"
              fi

              sleep 2
            done
          ''
        ];

        RunAtLoad = true;

        # Restart if the wrapper or nginx exits unexpectedly.
        KeepAlive = {
          SuccessfulExit = false;
        };

        ThrottleInterval = 10;

        # Do not make launchd enter the user's home directory before starting.
        WorkingDirectory = "/";

        # launchd opens these files before starting ProgramArguments.
        # Therefore they must not live under /Users/ven during early boot.
        StandardOutPath = "${systemPaths.logs}/${cfg.label}.out.log";
        StandardErrorPath = "${systemPaths.logs}/${cfg.label}.err.log";
      };
    };
  };
}
