# darwin/services/docker/nginx.nix
#
# =====================================================================
# NGINX
# 
# - Installs nginx from Nixpkgs.
# - Writes a main nginx.conf to:
#       ~/.config/conf/nginx.conf
# - Includes virtual hosts from:
#       ~/.config/conf/apps-enabled/*.conf
# - Logs to:
#       ~/.config/conf/logs/{access,error}.log
# - Provides a run-nginx-custom wrapper.
# - Creates a launchd daemon for privileged HTTP(S) ports:
#       com.ven.nginx-custom
# =====================================================================

{ config, pkgs, lib, ... }:

let
# ------------------------------------------------------- # 
# ------ USER VARIABLES ------ #
# ------------------------------------------------------- # 
  userHome = config.users.users.ven.home;

  confRoot   = "${userHome}/.config/nginx/";
  nginxConf  = "${confRoot}/nginx.conf";
  appsDir    = "${confRoot}/apps-enabled";
  logsDir    = "${confRoot}/logs";

  nginxBin   = "${pkgs.nginx}/bin/nginx";
  # ------------------------------------------------------- # 

  
  # ------------------------------------------------------- # 
  # ------ MAIN NGINX CONFIG (nginx.conf) ------ #
  mainConfig = ''
    # AUTO-GENERATED BY NIX - DO NOT EDIT BY HAND
    pid ${confRoot}/nginx.pid;
    error_log ${logsDir}/error.log;

    # Run request workers as the normal user after the root master binds ports.
    user ven staff;

    # ** Worker process means the number of worker processes that Nginx will spawn to handle incoming requests
    # ** The optimal number of worker processes depends on the number of CPU cores available on the system and the expected traffic load.
	# ** For a low-traffic environment, 1 worker process is sufficient. For a high-traffic environment, you may want to increase the number of worker processes to match the number of CPU cores available on the system.
    worker_processes  1;

    # ** Worker connections means the maximum number of simultaneous connections that each worker process can handle.
	# ** The optimal number of worker connections depends on the expected traffic load and the available system resources. For a low-traffic environment, 1024 worker connections is sufficient. For a high-traffic environment, you may want to increase the number of worker connections to handle more simultaneous connections.
    events {
      worker_connections 1024;
    }

    # ** The http block is the main configuration block for the HTTP server in Nginx. It contains directives that apply to all HTTP requests and responses, such as logging, MIME types, and connection settings.

    # ------------------------------------------------------- # 
    # ------ SET HTTP SERVER CONFIGURATION ------ #
    # Set up the HTTP server with logging, MIME types, and connection settings
    http {
      # Use nginx's own mime.types from Nix store
      include       ${pkgs.nginx}/conf/mime.types;

      # Set the default MIME type for files that do not have a specific MIME type defined
      default_type  application/octet-stream;

      # Set up logging format for access logs
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';

      # Set up access and error logs
      access_log  ${logsDir}/access.log  main;
      error_log   ${logsDir}/error.log;

      # Set up connection settings for keep-alive and timeouts
      sendfile        on;
      keepalive_timeout  65;

      # Per-app configs (Vaultwarden etc.)
      include ${appsDir}/*.conf;
    }
  '';
  # ------------------------------------------------------- # 

  # Change the LaunchDaemon plist whenever the generated main config changes.
  # nix-darwin reloads a daemon when its plist changes, not when a runtime
  # config file written during activation changes.
  mainConfigHash = builtins.hashString "sha256" mainConfig;

  nginxSetupScript = pkgs.writeShellScriptBin "nginx-setup" ''
    #!/usr/bin/env bash
    set -euo pipefail

    # Print messages for debugging
    echo ">>> [nginx] Creating config + folders"
    echo ">>> [nginx]   conf: ${confRoot}"
    echo ">>> [nginx]   apps: ${appsDir}"
    echo ">>> [nginx]   logs: ${logsDir}"

    # Ensure config + folders exist
    mkdir -p "${confRoot}" "${appsDir}" "${logsDir}"
    touch "${logsDir}/access.log" "${logsDir}/error.log"

    # Write main nginx.conf
    echo ">>> [nginx] Writing nginx.conf → ${nginxConf}"
    cat > "${nginxConf}" <<'EOF'
${mainConfig}
EOF
  '';
  # Runner script to start nginx with the custom config
  runner = pkgs.writeShellScriptBin "run-nginx-custom" ''
    #!/usr/bin/env bash
    set -euo pipefail

    echo ">>> [nginx] Starting nginx with ${nginxConf}"

    # Test config before starting
    "${nginxBin}" -t -c "${nginxConf}" || {
      echo "!!! [nginx] nginx -t FAILED for ${nginxConf}"
      
      # ** exit 78 means "configuration error" in nginx's exit codes
      exit 78
    }

    # Launch nginx with the custom config in the foreground (daemon off).
    # Keep arguments together: comments inside a continued shell command
    # would make Bash ignore the remaining Nginx arguments.
    echo ">>> [nginx] nginx -t OK, launching (daemon off)"
    exec "${nginxBin}" -e "${logsDir}/error.log" -g "daemon off;" -c "${nginxConf}"
  '';
in
{
  # Install nginx and helper scripts
  environment.systemPackages = [ pkgs.nginx nginxSetupScript runner ];

  # Stable wrapper path for launchd (avoids /nix/store path churn)
  environment.etc."ven/services/run-nginx-custom".source =

  	# Stable wrapper path for launchd (avoids /nix/store path churn)
    "${runner}/bin/run-nginx-custom";

  # Ensure folders + nginx.conf exist at activation
  system.activationScripts.extraActivation.text = lib.mkAfter ''
    echo ">>> Running nginx-setup"
    
    # Run the nginx-setup script to create the necessary directories and write the main nginx.conf
    ${nginxSetupScript}/bin/nginx-setup || echo "!!! nginx-setup failed (continuing)"
  '';

  # Launchd daemon: com.ven.nginx-custom
  # Nginx needs a root master process to bind ports 80 and 443.
  launchd.daemons.nginx-custom = {
    serviceConfig = {

      # Stable label for the launchd daemon
      # ** 'label' is a unique identifier for the launchd job, used to manage and control the service.
      Label            = "com.ven.nginx-custom";

      # Start through macOS' built-in Bash. The system LaunchDaemon may run
      # before /nix, /etc/ven, the user's home directory, nginx config, or
      # certificates are ready after boot.
      ProgramArguments = [
        "/bin/bash"
        "-c"
        ''
          set -u

          echo ">>> [nginx-launchd] Waiting for nginx files after boot"

          while true; do
            if [ -x /etc/ven/services/run-nginx-custom ] \
              && [ -f "${nginxConf}" ] \
              && [ -d "${appsDir}" ] \
              && [ -d "${logsDir}" ]
            then
              echo ">>> [nginx-launchd] Required paths are ready"
              exec /etc/ven/services/run-nginx-custom
            fi

            sleep 2
          done
        ''
      ];

      RunAtLoad = true;

      # Restart if the wrapper or nginx exits unexpectedly.
      KeepAlive = {
        SuccessfulExit = false;
      };

      ThrottleInterval = 10;

      # Do not make launchd enter the user's home directory before starting.
      WorkingDirectory = "/";

      # launchd opens these files before starting ProgramArguments.
      # Therefore they must not live under /Users/ven during early boot.
      StandardOutPath = "/var/log/com.ven.nginx-custom.out.log";
      StandardErrorPath = "/var/log/com.ven.nginx-custom.err.log";

      # Track generated configuration in the plist so a relevant rebuild
      # reloads this daemon after activation has written nginx.conf.
      EnvironmentVariables.NGINX_MAIN_CONFIG_HASH = mainConfigHash;
    };
  };
}
