# darwin/packages/claude/claude-desktop.nix

{

  # Collection of utility functions and definitions for Nix ecosystem
  lib,

  # Standard environment for building packages without a C compiler
  stdenvNoCC,

  # Fetches files from URLs and verifies their integrity using SHA256 hashes
  fetchurl,

  # cli tool for extracting zip files
  unzip,

  # Function to create shell applications with specified runtime inputs and script text
  writeShellApplication,

  # Collection of core utilities for file, shell, and text manipulation
  coreutils,

  # cli tool for transferring data with URLs
  curl,

  # cli tool for version control and source code management
  git,

  # cli tool for processing JSON data
  jq,

  # cli tool for managing Nix packages and environments
  nix,

  # App version
  version ? "1.24012.9",

  # App's release ID
  # ** 'release ID' is a unique identifier for each release of the Claude desktop application
  releaseId ? "03c61d06f8e01a4db2273b9514e225f21d2ba62e",

  # SHA256 hash of the downloaded zip file
  # ** This is used to verify the integrity of the downloaded file
  # ** The hash is generated by the update script and should be updated whenever a new version is released
  # ** 'sourceHash' is a SHA256 hash of the downloaded zip file, used to verify its integrity. It is generated by the update script and should be updated whenever a new version is released.
  sourceHash ? "sha256-Oa0tGB4rGwF8VQb2bAg5nCNXXIAti2OSf0ASjncQOps=",

  # URL to download the zip file for the specified version and release ID
  downloadUrl ? "https://downloads.claude.ai/releases/darwin/universal/${version}/Claude-${releaseId}.zip",

  applicationName ? "Claude.app",
}:

let
  # ------------------------------------------------------------
  # ------ CLAUDE DESKTOP UPDATE SCRIPT ------ #
  #
  # Provides all commands required by update-claude-desktop.sh
  # and exposes the resulting executable through:
  #
  # passthru.updateScript
  # 
  # NOTE: 
  # 	 The update script is a shell application that provides all the commands required by the update-claude-desktop.sh script. It is built using the writeShellApplication function, which allows us to specify the name of the application, its runtime inputs, and the text of the script itself. The resulting executable is then exposed through the passthru.updateScript attribute, allowing users to easily run the update script from their terminal.
  # ------------------------------------------------------------

  # Shell application for commands required by update-claude-desktop.sh
  # ** It allows for specifying: name of the application, runtime inputs, and the text of the script itself
  updateClaudeDesktop =
    writeShellApplication {
      # label for the update script
      name = "update-claude-desktop";
      
      # Runtime dependencies for the update script
      runtimeInputs = [
      	# Library of file, shell, and text manipulation utilities. It is required by the update script
      	# ** Used for performing various file operations, such as copying and moving files
        coreutils
        
        # cli tool for transferring data with URLs
        # ** Used by the update script to download files from the internet
        curl

        # cli tool for version control and source code management
		# ** Used by the update script to clone and manage Git repositories
        git

        # cli tool for processing JSON data
		# ** Used by the update script to parse and manipulate JSON data
        jq

        # cli tool for managing Nix packages and environments
		# ** Used by the update script to manage Nix packages and environments
        nix
      ];

      # The text of the update script itself, read from the update-claude-desktop.sh file
      text =
        builtins.readFile ./update-claude-desktop.sh;
    };
    # ------------------------------------------------------------

in

# ------------------------------------------------------------
# ------ CLAUDE DESKTOP APPLICATION PACKAGE ------ #
#
# This package provides the Claude desktop application bundle for macOS.
# It fetches the application bundle from the specified download URL, verifies its integrity using the provided SHA256 hash, and installs it into the /Applications directory.
# The package also exposes the update script through the passthru attribute, allowing users to easily update the application when a new version is released.
# ------------------------------------------------------------

# ---- APPLICATION BUNDLE FOR MACOS
stdenvNoCC.mkDerivation {
  pname = "claude-desktop";

  # Application's version to be installed
  # ** Specified earlier as a parameter to the derivation
  # ** Default: "1.24012.9"
  inherit version;

  # Application's releaseID to be installed
  # ** Specified earlier as a parameter to the derivation
  # ** Default: "03c61d06f8e01a4db2273b9514e225f21d2ba62e"
  inherit releaseId;

  # SHA256 hash of the downloaded zip file
  # ** Specified earlier as a parameter to the derivation
  # ** Default: "sha256-Oa0tGB4rGwF8VQb2bAg5nCNXXIAti2OSf0ASjncQOps="
  inherit sourceHash;
  src = fetchurl {
    url = downloadUrl;
    hash = sourceHash;
  };

  # The build inputs required for the derivation
  nativeBuildInputs = [
  	# cli tool for extracting zip files
    unzip
  ];

  # ** NOTE:
  # ** The application bundle is expected to be located in the root of the extracted zip file. Therefore, we set sourceRoot to "." to indicate that the source files are located in the current directory after extraction.
  # ** The build process for this derivation does not require any configuration or compilation steps, as it simply copies the application bundle to the output directory. Therefore, we set dontConfigure and dontBuild to true to skip these steps.

  # Application bundle already prebuilt - no configuration steps added (e.g., configure script, Makefile generation)
  dontConfigure = true;

  # Application bundle already prebuilt - no build steps added (e.g., compilation, linking)
  dontBuild = true;

  # Root directory for the derivation's source file
  # ** Set tp '.' as the source files are located in the current directory after extraction
  sourceRoot = ".";

  # Installation phase of the derivation
  # ** Copies the application bundle to the output directory
  installPhase = ''

  	# Run pre-installation hook
  	# ** Performs any necessary setup or checks before installing the application bundle
    runHook preInstall

    # Define the source and destination paths for the application bundle
    application_source="$PWD/${applicationName}"

    # Define the destination path for the application bundle in the output directory
    application_destination="$out/Applications/${applicationName}"

    # Check if the application bundle exists in the source directory
    if [ ! -d "$application_source" ]; then

      # Application bundle does not exist = Error message + Exit with a non-zero status code
      echo "ERROR: Claude application bundle was not found." >&2
      
      # Print the expected source path for the application bundle to stderr
      # ** This helps users understand where the script expected to find the application bundle, which can aid in troubleshooting
      # ** Error messages are printed to stderr using '>&2' to ensure that they are visible to the user even if stdout is redirected.
      # ** NOTE:
      # 'stderr' means "standard error" and is a separate output stream from 'stdout' (standard output). It is used for error messages and diagnostics, allowing users to distinguish between normal output and error messages.
      echo "Expected: $application_source" >&2

      # Error occured during execution of the install phase
      exit 1
    fi

    mkdir -p "$out/Applications"

    # Copy the application bundle to the output directory
    cp \
      # ... do so recursively, preserving file attributes and symbolic links
      -R \

      # ... preserve file attributes (e.g., timestamps, permissions) and symbolic links

      # Preserve symbolic links instead of copying the files they point to
      # ** If the source contains a symbolic link, the link itself will be copied rather than the file it points to. It's important for maintaining the structure of the application bundle, as it may contain symbolic links that are necessary for its proper functioning.
      # ** NOTE:
      # '--' means "end of options" and is used to indicate that any following arguments should be treated as positional parameters rather than options. This is important when dealing with file paths that may start with a hyphen (-), which could be interpreted as an option by the cp command.
      -- \
      
      # Copy the application bundle from the source path to the destination path
      "$application_source" \
      "$application_destination"

    # Check if the application bundle was successfully copied to the output directory
    if [ ! -d "$application_destination" ]; then
      echo "ERROR: Claude application bundle was not installed." >&2
      exit 1
    fi

    runHook postInstall
  '';
  # ------------------------------------------------------------

  
  # ------------------------------------------------------------
  # ------ EXPOSE UPDATE SCRIPT THROUGH PASSTHRU ------ #
  # ** The update script is exposed through the passthru attribute, allowing users to easily run the update script from their terminal. This is useful for users who want to update the Claude desktop application when a new version is released, as they can simply run the update script without having to manually download and install the new version.
  # ------------------------------------------------------------
  passthru = {
    updateScript =
      # Expose the update script through the passthru attribute
      # ** Allows for easy execution of the update script from the terminal
      "${updateClaudeDesktop}/bin/update-claude-desktop";

    # The update script package
    updateScriptPackage =
      updateClaudeDesktop;
  };
  # ------------------------------------------------------------


  
  # ------------------------------------------------------------
  # ------ METADATA FOR THE CLAUDE DESKTOP APPLICATION PACKAGE ------ #
  # ** Provides metadata about the package, including a description, homepage URL, license information, and supported platforms. This information is useful for users who want to learn more about the package, its licensing terms, and its compatibility with different operating systems.
  # ------------------------------------------------------------
  meta = {
  	# A brief description of the package
    description = "Anthropic's official Claude AI desktop application";

    # The homepage URL for the package
    homepage = "https://claude.com/download";

    # The license information for the package
    license = lib.licenses.unfree;

    # ---- PACKAGE'S SOURECE PROVENANCE
    sourceProvenance = [
      # Binary native code package
      # ** Source code is not available and the package is distributed as precompiled binaries
      lib.sourceTypes.binaryNativeCode
    ];

    # Supported platforms for the package
    platforms = lib.platforms.darwin;

    # The main program provided by the package
    mainProgram = "Claude";
  };
  # ------------------------------------------------------------

}