# /Users/ven/dotfiles/nix/darwin/modules/services/vaultwarden-nginx.nix
#
# NGINX VIA HOMEBREW (DECLARATIVE CONFIG)
# ============================================================
# - nginx installed via nix-homebrew
# - config generated by Nix into /opt/homebrew/etc/nginx/nginx.conf
# - certificate generated if missing
# - you start nginx with:  brew services restart nginx
# ============================================================

{ config, pkgs, ... }:

let
  nginxConf = ''
    # ============================================================
    # NGINX BASE CONFIG
    # ============================================================
    worker_processes  1;
    events { worker_connections  1024; }

    http {
      include       mime.types;
      default_type  application/octet-stream;

      sendfile        on;
      keepalive_timeout  65;

      # ============================================================
      # SELF-SIGNED CERT FOR vaultwarden.local
      # ============================================================
      server {
        listen 443 ssl;
        server_name vaultwarden.local;

        ssl_certificate      /Users/ven/dotfiles/ssl/vaultwarden/cert.pem;
        ssl_certificate_key  /Users/ven/dotfiles/ssl/vaultwarden/key.pem;

        location / {
          proxy_pass http://127.0.0.1:8080;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
        }
      }

      # ============================================================
      # Allow plain HTTP redirecting to HTTPS
      # ============================================================
      server {
        listen 80;
        server_name vaultwarden.local;
        return 301 https://vaultwarden.local$request_uri;
      }
    }
  '';

  certDir = "/Users/ven/dotfiles/ssl/vaultwarden";
  cert    = "${certDir}/cert.pem";
  key     = "${certDir}/key.pem";
in
{
  # Write nginx.conf declaratively
  environment.etc."nginx/nginx.conf".text = nginxConf;

  # Generate self-signed cert if missing
  system.activationScripts.vaultwardenNginxCert.text = ''
    mkdir -p ${certDir}

    if [ ! -f "${cert}" ] || [ ! -f "${key}" ]; then
      echo "Generating self-signed certificate for vaultwarden.local..."
      ${pkgs.openssl}/bin/openssl req -x509 -nodes -newkey rsa:2048 \
        -keyout "${key}" \
        -out "${cert}" \
        -subj "/CN=vaultwarden.local" \
        -days 365
    fi
  '';

  # Tell user to restart Brew nginx after rebuild
  system.activationScripts.vaultwardenNginxMessage.text = ''
    echo ""
    echo "=== NOTE ==="
    echo "Run:  brew services restart nginx"
    echo "==============================="
  '';
}
