# /Users/ven/dotfiles/nix/darwin/modules/services/vaultwarden-nginx.nix
#
# NGINX VIA HOMEBREW (DECLARATIVE CONFIG)
# ============================================================
# - nginx installed from Homebrew via nix-homebrew
# - config generated by Nix
# - nginx launched/managed via `brew services`
# - Self-signed TLS for https://vaultwarden.local
# ============================================================

{ config, pkgs, ... }:

let
  certDir = "/Users/ven/dotfiles/ssl/vaultwarden";
  cert    = "${certDir}/cert.pem";
  key     = "${certDir}/key.pem";

  nginxConf = ''
    worker_processes 1;

    events {
      worker_connections 1024;
    }

    http {
      include       mime.types;
      default_type  application/octet-stream;

      sendfile on;
      keepalive_timeout 65;

      # ============================================================
      # HTTPS reverse proxy for Vaultwarden
      # ============================================================
      server {
        listen 443 ssl;
        server_name vaultwarden.local;

        ssl_certificate      ${cert};
        ssl_certificate_key  ${key};

        location / {
          proxy_pass http://127.0.0.1:8080;

          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;
        }
      }

      # Redirect HTTP to HTTPS
      server {
        listen 80;
        server_name vaultwarden.local;
        return 301 https://vaultwarden.local$request_uri;
      }
    }
  '';
in
{
  # Write nginx.conf via Nix -> Homebrew will use it
  environment.etc."nginx/nginx.conf".text = nginxConf;

  # Generate self-signed cert (once)
  system.activationScripts.vaultwardenCert.text = ''
    mkdir -p ${certDir}

    if [ ! -f "${cert}" ] || [ ! -f "${key}" ]; then
      echo "Generating self-signed certificate for vaultwarden.local..."
      ${pkgs.openssl}/bin/openssl req -x509 -nodes -newkey rsa:2048 \
        -keyout "${key}" \
        -out "${cert}" \
        -subj "/CN=vaultwarden.local" \
        -days 365
    fi
  '';

  # Friendly reminder after rebuild
  system.activationScripts.vaultwardenNginxMessage.text = ''
    echo ">> Restarting nginx recommended:   brew services restart nginx"
  '';
}
