# options/pkgs-configs/espanso/default.nix
#
# =====================================================================
# ESPANSO: FEATURE DEFINITION
#
# Defines Espanso's parent feature schema, renders the Nix-owned
# config/default.yml and match/base.yml files, and starts Espanso at
# login through Home Manager (launchd on Darwin, systemd on Linux).
# Concrete values are selected in shared/home/default.nix.
# =====================================================================

{ config, lib, paths, pkgs, ... }:

let
  cfg = config.ven.espanso;

  # Espanso's own default directory differs per platform, so both launchers
  # point it at the directory Home Manager populates.
  espansoRoot = "${config.home.homeDirectory}/${paths.relative.espanso.root}";
  espansoEnvironment = {
    ESPANSO_CONFIG_DIR = espansoRoot;
    ESPANSO_DATA_DIR = "${espansoRoot}/data";
  };
in

{
  # ------------------------------------------------------------
  # ------ ESPANSO FEATURE DEFINITIONS ------ #
  # Markdown is an independent Espanso subfeature with its own option
  # schema in this same options directory.

  imports = [
    ./markdown.nix
  ];

  options.ven.espanso = {
    enable = lib.mkEnableOption "Espanso configuration";

    autostart.enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Start Espanso at login (launchd on Darwin, systemd on Linux).";
    };

    showNotifications = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Show Espanso expansion notifications.";
    };

    base.enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Create Espanso's base match file.";
    };
  };

  config = lib.mkMerge [
    {
      # ------------------------------------------------------------
      # ------ ESPANSO BASE CONFIGURATION ------ #
      # Home Manager links these immutable, Nix-generated files into
      # Espanso's portable configuration directory.

      home.file.${paths.relative.espanso.defaultConfig} = lib.mkIf cfg.enable {
        text = ''
          # This file is generated by Nix. Edit shared/home/default.nix.
          show_notifications: ${
            if cfg.showNotifications
            then "true"
            else "false"
          }
        '';
      };

      home.file.${paths.relative.espanso.baseMatches} = lib.mkIf (
        cfg.enable && cfg.base.enable
      ) {
        text = ''
          # This file is generated by Nix. Edit options/pkgs-configs/espanso.
          matches: []
        '';
      };
    }

    # ------------------------------------------------------------
    # ------ DARWIN ESPANSO LAUNCH AGENT ------ #
    # Uses the Nix package binary rather than the mutable /Applications
    # symlink.

    (lib.mkIf (cfg.enable && cfg.autostart.enable && pkgs.stdenv.isDarwin) {
      launchd.agents.espanso = {
        enable = true;
        config = {
          Label = "com.federicoterzi.espanso";
          ProgramArguments = [
            "${pkgs.espanso}/bin/espanso"
            "launcher"
          ];
          RunAtLoad = true;
          EnvironmentVariables = espansoEnvironment;
        };
      };
    })

    # ------------------------------------------------------------
    # ------ LINUX ESPANSO USER SERVICE ------ #
    # Starts Espanso with the graphical session.

    (lib.mkIf (cfg.enable && cfg.autostart.enable && pkgs.stdenv.isLinux) {
      systemd.user.services.espanso = {
        Unit = {
          Description = "Espanso text expander";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
        };

        Service = {
          ExecStart = "${pkgs.espanso}/bin/espanso launcher";
          Environment = lib.mapAttrsToList (name: value: "${name}=${value}") espansoEnvironment;
          Restart = "on-failure";
        };

        Install.WantedBy = [ "graphical-session.target" ];
      };
    })
  ];
}
