#!/usr/bin/env bash

set -euo pipefail

# ------------------------------------------------------------
# ------ CLAUDE DESKTOP UPDATE SETTINGS ------ #
# ------------------------------------------------------------

release_manifest_url="https://downloads.claude.ai/releases/darwin/universal/RELEASES.json"

package_relative_directory="darwin/modules/system/packages/claude"
release_file_name="claude-desktop-release.nix"

archive_prefix="Claude-"
archive_suffix=".zip"

# ------------------------------------------------------------
# ------ REQUIRED COMMANDS ------ #
# ------------------------------------------------------------

required_commands=(
  cmp
  curl
  git
  jq
  mktemp
  mv
  nix
  rm
)

for required_command in "${required_commands[@]}"
do
  if ! command -v "$required_command" >/dev/null 2>&1
  then
    echo "Missing required command: $required_command" >&2
    exit 1
  fi
done

# ------------------------------------------------------------
# ------ REPOSITORY PATHS ------ #
# ------------------------------------------------------------

repository_root="$(
  git rev-parse --show-toplevel 2>/dev/null
)" || {
  echo "Could not find the Nix configuration repository." >&2
  echo "Run this updater from inside the repository." >&2
  exit 1
}

package_directory="$repository_root/$package_relative_directory"
release_file="$package_directory/$release_file_name"

if [[ ! -d "$package_directory" ]]
then
  echo "Claude package directory was not found:" >&2
  echo "$package_directory" >&2
  exit 1
fi

# ------------------------------------------------------------
# ------ TEMPORARY WORKSPACE ------ #
# ------------------------------------------------------------

temporary_directory="$(
  mktemp -d -t claude-desktop-update
)"

cleanup() {
  rm \
    -rf \
    -- \
    "$temporary_directory"
}

trap cleanup EXIT

manifest_file="$temporary_directory/RELEASES.json"
new_release_file="$temporary_directory/$release_file_name"

# ------------------------------------------------------------
# ------ FETCH LATEST RELEASE INFORMATION ------ #
# ------------------------------------------------------------

echo "Downloading Claude Desktop release manifest."

curl \
  --fail \
  --silent \
  --show-error \
  --location \
  "$release_manifest_url" \
  --output "$manifest_file"

version="$(
  jq \
    --exit-status \
    --raw-output \
    '.currentRelease' \
    "$manifest_file"
)"

if [[ -z "$version" || "$version" == "null" ]]
then
  echo "Claude Desktop version was not found." >&2
  exit 1
fi

download_url="$(
  jq \
    --exit-status \
    --raw-output \
    --arg version "$version" \
    '
      first(
        .releases[]
        | select(.version == $version)
        | .updateTo.url
      )
    ' \
    "$manifest_file"
)"

if [[ -z "$download_url" || "$download_url" == "null" ]]
then
  echo "Claude Desktop download URL was not found." >&2
  exit 1
fi

# ------------------------------------------------------------
# ------ VALIDATE DOWNLOAD URL ------ #
# ------------------------------------------------------------

expected_url_prefix="https://downloads.claude.ai/releases/darwin/universal/$version/$archive_prefix"

case "$download_url" in
  "$expected_url_prefix"*"$archive_suffix")
    ;;
  *)
    echo "Claude Desktop returned an unexpected download URL:" >&2
    echo "$download_url" >&2
    exit 1
    ;;
esac

# ------------------------------------------------------------
# ------ EXTRACT RELEASE IDENTIFIER ------ #
# ------------------------------------------------------------

archive_name="${download_url##*/}"

release_id="${archive_name#"$archive_prefix"}"
release_id="${release_id%"$archive_suffix"}"

if [[ -z "$release_id" || "$release_id" == "$archive_name" ]]
then
  echo "Could not extract the Claude Desktop release ID." >&2
  echo "Archive: $archive_name" >&2
  exit 1
fi

# ------------------------------------------------------------
# ------ CALCULATE NIX SOURCE HASH ------ #
# ------------------------------------------------------------

echo "Prefetching Claude Desktop $version."

prefetch_result="$(
  nix \
    --extra-experimental-features "nix-command flakes" \
    store prefetch-file \
    --json \
    --hash-type sha256 \
    "$download_url"
)"

source_hash="$(
  printf '%s\n' "$prefetch_result" |
    jq \
      --exit-status \
      --raw-output \
      '.hash'
)"

if [[ -z "$source_hash" || "$source_hash" == "null" ]]
then
  echo "Nix source hash was not returned." >&2
  exit 1
fi

# ------------------------------------------------------------
# ------ GENERATE RELEASE FILE ------ #
# ------------------------------------------------------------

cat >"$new_release_file" <<EOF
# /Users/ven/.config/nix/nix-config/darwin/modules/system/packages/claude/claude-desktop-release.nix
#
# Generated by update-claude-desktop.sh.

{
  version = "$version";
  releaseId = "$release_id";
  sourceHash = "$source_hash";
  downloadUrl = "$download_url";
}
EOF

# ------------------------------------------------------------
# ------ APPLY UPDATE ------ #
# ------------------------------------------------------------

if [[ -f "$release_file" ]] &&
  cmp \
    --silent \
    "$new_release_file" \
    "$release_file"
then
  echo "Claude Desktop is already current: $version"
  exit 0
fi

mv \
  -- \
  "$new_release_file" \
  "$release_file"

echo
echo "Claude Desktop release information updated."
echo "Version: $version"
echo "Release ID: $release_id"
echo "Hash: $source_hash"
echo
echo "Updated file:"
echo "$release_file"