# options/package-options/espanso/default.nix
#
# =====================================================================
# ESPANSO: FEATURE DEFINITION
#
# Defines Espanso's parent feature schema, renders the Nix-owned
# config/default.yml and match/base.yml files, and starts Espanso at
# login through Home Manager (launchd on Darwin, systemd on Linux).
# Concrete values are selected in shared/home/default.nix.
# =====================================================================

{
  config,
  lib,
  paths,
  pkgs,
  platforms,
  ...
}:

let
  cfg = config.home.shared.espanso;

  # Espanso's own default directory differs per platform, so both launchers
  # point it at the directory Home Manager populates.
  espansoRoot = "${config.home.homeDirectory}/${paths.relative.espanso.root}";
  espansoEnvironment = {
    ESPANSO_CONFIG_DIR = espansoRoot;
    ESPANSO_DATA_DIR = "${espansoRoot}/data";
  };
  enabledForCurrentPlatform = platforms.enabledForCurrentPlatform {
    enable = cfg.enable;
    installOn = cfg.installOn;
  };
in

{
  # ------------------------------------------------------------
  # ------ ESPANSO FEATURE DEFINITIONS ------ #
  # Markdown is an independent Espanso subfeature with its own option
  # schema in this same options directory.

  imports = [
    ./markdown.nix
  ];

  options.home.shared.espanso = {
    enable = lib.mkEnableOption "Espanso configuration";

    installOn = lib.mkOption {
      type = lib.types.attrsOf lib.types.bool;
      default = {
        darwin = true;
        linux = true;
      };
      description = "Platforms on which Home Manager configures and starts Espanso.";
    };

    autostart = {
      enable = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = "Start Espanso at login (launchd on Darwin, systemd on Linux).";
      };

      restartOnCrash = lib.mkOption {
        type = lib.types.bool;
        default = true;
        description = ''
          Restart the autostarted Espanso when it crashes or exits with an
          error. Quitting it normally does not restart it. Rendered as
          KeepAlive on Darwin and Restart=on-failure on Linux.
        '';
      };
    };

    showNotifications = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Show Espanso expansion notifications.";
    };

    base.enable = lib.mkOption {
      type = lib.types.bool;
      default = true;
      description = "Create Espanso's base match file.";
    };
  };

  config = lib.mkMerge [
    {
      # ------------------------------------------------------------
      # ------ ESPANSO BASE CONFIGURATION ------ #
      # Espanso's mutable configuration and user launcher are Home Manager
      # concerns. Its package and Darwin application bundle stay system-owned
      # in shared/packages.nix.

      # Home Manager links these immutable, Nix-generated files into
      # Espanso's portable configuration directory.

      home.file.${paths.relative.espanso.defaultConfig} = lib.mkIf cfg.enable {
        text = ''
          # This file is generated by Nix. Edit shared/home/default.nix.
          show_notifications: ${if cfg.showNotifications then "true" else "false"}
        '';
      };

      home.file.${paths.relative.espanso.baseMatches} = lib.mkIf (cfg.enable && cfg.base.enable) {
        text = ''
          # This file is generated by Nix. Edit options/package-options/espanso.
          matches: []
        '';
      };
    }

    # ------------------------------------------------------------
    # ------ DARWIN ESPANSO LAUNCH AGENT ------ #
    # Runs the executable inside the Nix store Espanso.app bundle so TCC
    # attributes it to Espanso.app, not a bare "espanso" binary.

    (lib.mkIf (enabledForCurrentPlatform && cfg.autostart.enable && platforms.isDarwin) {
      launchd.agents.espanso = {
        enable = true;
        config = {
          Label = "com.federicoterzi.espanso";
          ProgramArguments = [
            "${pkgs.espanso}/Applications/Espanso.app/Contents/MacOS/espanso"
            "launcher"
          ];
          RunAtLoad = true;
          EnvironmentVariables = espansoEnvironment;

          # Same rule as systemd's on-failure: relaunch after a non-zero exit
          # or a crash signal, never after a clean quit.
          KeepAlive =
            if cfg.autostart.restartOnCrash then
              {
                SuccessfulExit = false;
                Crashed = true;
              }
            else
              null;
        };
      };
    })

    # ------------------------------------------------------------
    # ------ LINUX ESPANSO USER SERVICE ------ #
    # Starts Espanso with the graphical session.

    (lib.mkIf (enabledForCurrentPlatform && cfg.autostart.enable && platforms.isLinux) {
      systemd.user.services.espanso = {
        Unit = {
          Description = "Espanso text expander";
          PartOf = [ "graphical-session.target" ];
          After = [ "graphical-session.target" ];
        };

        Service = {
          ExecStart = "${pkgs.espanso}/bin/espanso launcher";
          Environment = lib.mapAttrsToList (name: value: "${name}=${value}") espansoEnvironment;
          Restart = if cfg.autostart.restartOnCrash then "on-failure" else "no";
        };

        Install.WantedBy = [ "graphical-session.target" ];
      };
    })
  ];
}
