# /Users/ven/.config/nix/nix-darwin/darwin/modules/services/docker/vaultwarden/vaultwarden-nginx.nix
#
# VAULTWARDEN: NGINX REVERSE PROXY (CUSTOM)
# =========================================
# - Writes a per-app nginx config to:
#       $HOME/ven-dots/conf/apps-enabled/vaultwarden.conf
# - Terminates TLS for:
#       vaultwarden.local
#       192.168.2.125
# - Proxies to Vaultwarden on 127.0.0.1:${hostPort}
# - Supports WebSockets + headers
# =========================================

{ config, pkgs, lib, ... }:

let
  userHome = config.users.users.ven.home;

  confRoot = "${userHome}/ven-dots/conf";
  appsDir  = "${confRoot}/apps-enabled";

  certDir = "${userHome}/ven-dots/ssl/vaultwarden";
  certPem = "${certDir}/vaultwarden.local.pem";
  keyPem  = "${certDir}/vaultwarden.local-key.pem";

  hostPort = config.ven.vaultwarden.hostPort or 8080;

  vhostFile = "${appsDir}/vaultwarden.conf";

  vhostConfig = ''
    # AUTO-GENERATED BY NIX
    # Vaultwarden reverse proxy

    # HTTP → HTTPS redirects (hostname)
    server {
      listen 80;
      server_name vaultwarden.local;
      return 301 https://vaultwarden.local$request_uri;
    }

    # HTTP → HTTPS redirects (IP)
    server {
      listen 80;
      server_name 192.168.2.125;
      return 301 https://192.168.2.125$request_uri;
    }

    # Main HTTPS server
    server {
      listen 443 ssl;
      server_name vaultwarden.local 192.168.2.125;

      ssl_certificate     ${certPem};
      ssl_certificate_key ${keyPem};

      # Optional: stronger TLS settings could go here later

      location / {
        proxy_pass              http://127.0.0.1:${toString hostPort};
        proxy_http_version      1.1;
        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        "upgrade";
      }
    }
  '';
in
{
  system.activationScripts.vaultwarden-nginx-conf.text = lib.mkAfter ''
    echo ">>> [vaultwarden-nginx] Writing nginx vhost to ${vhostFile}"
    mkdir -p "${appsDir}"

    cat > "${vhostFile}" <<'EOF'
${vhostConfig}
EOF
  '';
}
