# /Users/ven/.config/nix/nix-darwin/darwin/modules/services/docker/vaultwarden/vaultwarden-nginx.nix
#
# VAULTWARDEN: NGINX VHOST (DARWIN)
# =================================
# - Writes Vaultwarden nginx config to:
#       ~/.config/nginx/apps-enabled/vaultwarden.conf
# - Proxies HTTPS traffic for:
#       vaultwarden.local
#       192.168.2.125
# - Uses mkcert certificate files from:
#       ~/.config/ssl/vaultwarden
# - Redirects HTTP -> HTTPS
# - Supports Vaultwarden websocket traffic
# =================================

{ config, pkgs, lib, ... }:

let
  userName = "ven";
  userHome = config.users.users.${userName}.home;

  appName = "vaultwarden";

  nginxAppsDir = "${userHome}/.config/nginx/apps-enabled";
  vhostConf    = "${nginxAppsDir}/${appName}.conf";

  hostPort = config.ven.vaultwarden.hostPort or 8080;

  certDir = "${userHome}/.config/ssl/vaultwarden";
  certPem = "${certDir}/vaultwarden.local.pem";
  keyPem  = "${certDir}/vaultwarden.local-key.pem";

  serverNames = "vaultwarden.local 192.168.2.125";

  vhostConfig = ''
    # AUTO-GENERATED BY NIX - DO NOT EDIT BY HAND

    # ------------------------------------------------------------
    # HTTP -> HTTPS REDIRECT
    # ------------------------------------------------------------
    server {
      listen 80;
      listen [::]:80;
      server_name ${serverNames};

      return 301 https://$host$request_uri;
    }

    # ------------------------------------------------------------
    # HTTPS REVERSE PROXY
    # ------------------------------------------------------------
    server {
      listen 443 ssl;
      listen [::]:443 ssl;
      server_name ${serverNames};

      ssl_certificate     ${certPem};
      ssl_certificate_key ${keyPem};

      ssl_session_timeout 1d;
      ssl_session_cache shared:SSL:10m;
      ssl_session_tickets off;

      ssl_protocols TLSv1.2 TLSv1.3;
      ssl_prefer_server_ciphers off;

      client_max_body_size 128M;

      # ----------------------------------------------------------
      # MAIN VAULTWARDEN APP
      # ----------------------------------------------------------
      location / {
        proxy_pass http://127.0.0.1:${toString hostPort};

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        $connection_upgrade;
      }

      # ----------------------------------------------------------
      # WEBSOCKET ENDPOINT
      # ----------------------------------------------------------
      location /notifications/hub {
        proxy_pass http://127.0.0.1:${toString hostPort};

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
        proxy_set_header Upgrade           $http_upgrade;
        proxy_set_header Connection        $connection_upgrade;
      }

      location /notifications/hub/negotiate {
        proxy_pass http://127.0.0.1:${toString hostPort};

        proxy_set_header Host              $host;
        proxy_set_header X-Real-IP         $remote_addr;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;

        proxy_http_version 1.1;
      }
    }
  '';

  writeVhostScript = pkgs.writeShellScriptBin "vaultwarden-nginx-setup" ''
    #!/usr/bin/env bash
    set -euo pipefail

    echo ">>> [vw-nginx] START vaultwarden nginx setup"
    echo ">>> [vw-nginx] nginx apps dir: ${nginxAppsDir}"
    echo ">>> [vw-nginx] target conf:    ${vhostConf}"
    echo ">>> [vw-nginx] cert file:      ${certPem}"
    echo ">>> [vw-nginx] key file:       ${keyPem}"

    mkdir -p "${nginxAppsDir}"

    if [ ! -f "${certPem}" ]; then
      echo "!!! [vw-nginx] Missing certificate: ${certPem}"
      exit 1
    fi

    if [ ! -f "${keyPem}" ]; then
      echo "!!! [vw-nginx] Missing certificate key: ${keyPem}"
      exit 1
    fi

    cat > "${vhostConf}" <<'EOF'
map $http_upgrade $connection_upgrade {
  default upgrade;
  ''      close;
}

${vhostConfig}
EOF

    chown "${userName}:staff" "${vhostConf}" || {
      echo "!!! [vw-nginx] chown failed (continuing)"
    }

    chmod 644 "${vhostConf}" || {
      echo "!!! [vw-nginx] chmod failed (continuing)"
    }

    echo ">>> [vw-nginx] DONE vaultwarden nginx setup"
  '';
in
{
  environment.systemPackages = [ writeVhostScript ];

  system.activationScripts.extraActivation.text = lib.mkAfter ''
    echo ">>> Running vaultwarden-nginx-setup"
    ${writeVhostScript}/bin/vaultwarden-nginx-setup || echo "!!! vaultwarden-nginx-setup failed (continuing)"
  '';
}
