# darwin/services/docker/vaultwarden/vaultwarden-nginx.nix
#
# =====================================================================
# VAULTWARDEN: NGINX VHOST
# 
# - Writes Vaultwarden nginx config to:
#       ~/.config/nginx/apps-enabled/vaultwarden.conf
# - Proxies HTTPS traffic for:
#       vaultwarden.local
#       192.168.2.125
# - Uses mkcert certificate files from:
#       ~/.config/ssl/vaultwarden
# - Redirects HTTP -> HTTPS
# - Supports Vaultwarden websocket traffic
# =====================================================================

{ config, pkgs, lib, ... }:

let
  # User home directory
  userName = "ven";
  userHome = config.users.users.${userName}.home;

  # Vaultwarden nginx app name
  appName = "vaultwarden";
  
  # Vaultwarden nginx config directory
  nginxAppsDir = "${userHome}/.config/nginx/apps-enabled";

  # Vaultwarden nginx config file
  vhostConf = "${nginxAppsDir}/${appName}.conf";

  # Vaultwarden host port (default 8080)
  hostPort = config.ven.vaultwarden.hostPort or 8080;

  # Vaultwarden SSL certs directory
  certDir = "${userHome}/.config/ssl/vaultwarden";

  # Vaultwarden SSL cert + key
  certPem = "${certDir}/vaultwarden.local.pem";

  # Vaultwarden SSL key
  keyPem = "${certDir}/vaultwarden.local-key.pem";

  # Server names for nginx vhost
  serverNames = "vaultwarden.local 192.168.2.125";

  # Generated nginx vhost configuration
  generatedConf = ''
    # AUTO-GENERATED BY NIX - DO NOT EDIT BY HAND

    map $http_upgrade $connection_upgrade {
      # ** Set the default value for the connection upgrade header to "upgrade", which is required for WebSocket connections.
      # ** It's an optional directive that specifies the default value for the connection upgrade header if it is not set in the request. This is useful for WebSocket connections, which require the connection upgrade header to be set to "upgrade". By setting the default value to "upgrade", we ensure that WebSocket connections will work even if the client does not set the connection upgrade header.
      default upgrade;
      ""      close;
    }

    # ---- HTTP -> HTTPS REDIRECT
    server {
      # Listen on port 80 for both IPv4 and IPv6
      listen 80;

      # Listen on port 80 for both IPv4 and IPv6
      listen [::]:80;

      # Set the server name to match the Vaultwarden domain and IP address
      server_name ${serverNames};

      # Redirect all HTTP requests to HTTPS
      return 301 https://$host$request_uri;
    }

    # ------------------------------------------------------------
    # HTTPS REVERSE PROXY
    # ------------------------------------------------------------
    server {
      # Listen on port 443 for both IPv4 and IPv6 with SSL enabled
      listen 443 ssl;
      listen [::]:443 ssl;
      server_name ${serverNames};

      # Use the mkcert-generated certificate and key for SSL
      ssl_certificate ${certPem};
      ssl_certificate_key ${keyPem};

      # Set SSL session parameters for better performance and security
      ssl_session_timeout 1d;

      # Set the SSL session cache to shared memory with a size of 10MB
      ssl_session_cache shared:SSL:10m;

      # Disable SSL session tickets for improved security
      ssl_session_tickets off;

      # Set the preferred SSL protocols to TLSv1.2 and TLSv1.3 for better security
      ssl_protocols TLSv1.2 TLSv1.3;

      # Set the preferred cipher suites for TLSv1.2 and TLSv1.3
      ssl_prefer_server_ciphers off;

      # Set the maximum allowed size of the client request body to 128MB
      client_max_body_size 128M;

      # ----------------------------------------------------------
      # MAIN VAULTWARDEN APP
      # ----------------------------------------------------------
      location / {
      	# Proxy requests to the Vaultwarden backend
        proxy_pass http://127.0.0.1:${toString hostPort};

        # ---- SET HEADERS FOR WEBSOCKET SUPPORT
    
        # Set the Host header to the original host requested by the client
        proxy_set_header Host $host;

        # Set the X-Real-IP header to the original client IP address
        proxy_set_header X-Real-IP $remote_addr;

        # Set the X-Forwarded-For header to include the original client IP address
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Set the X-Forwarded-Proto header to indicate the original protocol (HTTP or HTTPS)
        proxy_set_header X-Forwarded-Proto $scheme;

        # Use HTTP/1.1 for WebSocket connections
        proxy_http_version 1.1;

        # Set the Upgrade and Connection headers to support WebSocket connections
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
      }

      # ----------------------------------------------------------
      # WEBSOCKET ENDPOINT
      # ----------------------------------------------------------
      location /notifications/hub {
        proxy_pass http://127.0.0.1:${toString hostPort};

        # ---- SET HEADERS FOR WEBSOCKET SUPPORT
        
        # Set the Host header to the original host requested by the client
        proxy_set_header Host $host;

        # Set the X-Real-IP header to the original client IP address
        proxy_set_header X-Real-IP $remote_addr;

        # Set the X-Forwarded-For header to include the original client IP
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Set the X-Forwarded-Proto header to indicate the original protocol (HTTP or HTTPS)
        proxy_set_header X-Forwarded-Proto $scheme;

        # Use HTTP/1.1 for WebSocket connections
        proxy_http_version 1.1;

        # Set the Upgrade and Connection headers to support WebSocket connections
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
      }

      # Use the same proxy settings for the negotiate endpoint
      location /notifications/hub/negotiate {
        proxy_pass http://127.0.0.1:${toString hostPort};

        # Set headers for WebSocket support
        proxy_set_header Host $host;

        # Set headers for WebSocket support
        proxy_set_header X-Real-IP $remote_addr;
        
        # Set the X-Forwarded-For header to include the original client IP
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Set the X-Forwarded-Proto header to indicate the original protocol (HTTP or HTTPS)
        proxy_set_header X-Forwarded-Proto $scheme;

        # Use HTTP/1.1 for WebSocket connections
        proxy_http_version 1.1;
      }
    }
  '';

  writeVhostScript = pkgs.writeShellScriptBin "vaultwarden-nginx-setup" ''
    set -euo pipefail

    # Print a message to indicate what this script is doing
    echo ">>> [vw-nginx] START vaultwarden nginx setup"
    echo ">>> [vw-nginx] nginx apps dir: ${nginxAppsDir}"
    echo ">>> [vw-nginx] target conf:    ${vhostConf}"
    echo ">>> [vw-nginx] cert file:      ${certPem}"
    echo ">>> [vw-nginx] key file:       ${keyPem}"

    mkdir -p "${nginxAppsDir}"

    # Check for the existence of the certificate and key files
    if [ ! -f "${certPem}" ]; then
      echo "!!! [vw-nginx] Missing certificate: ${certPem}"
      exit 1
    fi

    # Check for the existence of the key file
    if [ ! -f "${keyPem}" ]; then
      echo "!!! [vw-nginx] Missing certificate key: ${keyPem}"
      exit 1
    fi

    # Write the generated nginx vhost configuration to the target file
    cat > "${vhostConf}" <<'EOF'
${generatedConf}
EOF
	# Set ownership and permissions for the vhost configuration file
    chown "${userName}:staff" "${vhostConf}" || {

      # Set ownership and permissions for the vhost configuration file
      echo "!!! [vw-nginx] chown failed (continuing)"
    }
    # Set permissions to be readable by user (and others) so nginx can read it
    chmod 644 "${vhostConf}" || {

      # Set permissions to be readable by user (and others) so nginx can read it
      echo "!!! [vw-nginx] chmod failed (continuing)"
    }

    # Print a message to indicate that the setup is complete
    echo ">>> [vw-nginx] DONE vaultwarden nginx setup"
  '';
in
{
  # Generated script to write the nginx vhost configuration for Vaultwarden
  environment.systemPackages = [ writeVhostScript ];

  # Run the vaultwarden-nginx-setup script at activation to ensure the vhost is created
  system.activationScripts.extraActivation.text = lib.mkAfter ''
    echo ">>> Running vaultwarden-nginx-setup"

    # Run the vaultwarden-nginx-setup script to create the nginx vhost configuration
    ${writeVhostScript}/bin/vaultwarden-nginx-setup || echo "!!! vaultwarden-nginx-setup failed (continuing)"
  '';
}