# darwin/services/docker/vaultwarden/vaultwarden-nginx.nix
#
# =====================================================================
# VAULTWARDEN: NGINX VHOST
#
# - Registers the Vaultwarden vhost with the shared nginx module:
#       ven.nginx.virtualHosts.vaultwarden
# - nginx.nix renders it into the Nix store and links it to:
#       /etc/nginx/apps-enabled/vaultwarden.conf
# - Proxies HTTPS traffic for:
#       vaultwarden.local
#       192.168.2.125
# - Uses mkcert certificate files from:
#       ~/.config/ssl/vaultwarden
#   Those stay outside the Nix store: a private key must never be
#   world-readable in /nix/store.
# - Supports Vaultwarden websocket traffic
#
# This module only supplies configuration text. Writing the file,
# validating it and reloading nginx are all owned by nginx.nix.
# =====================================================================

{ config, ... }:

let
  # Shared path roots
  paths = import ../../../../options/paths.nix { };

  # Vaultwarden nginx app name
  appName = "vaultwarden";

  # Vaultwarden host port (default 8080)
  hostPort = config.ven.vaultwarden.hostPort or 8080;

  # Vaultwarden SSL certs directory
  certDir = "${paths.darwin.home.ssl}/${appName}";

  # Vaultwarden SSL cert + key
  certPem = "${certDir}/${appName}.local.pem";

  # Vaultwarden SSL key
  keyPem = "${certDir}/${appName}.local-key.pem";

  # Server names for nginx vhost
  serverNames = "vaultwarden.local 192.168.2.125";

  # Generated nginx vhost configuration
  generatedConf = ''
    # AUTO-GENERATED BY NIX - DO NOT EDIT BY HAND
    # Source: darwin/services/docker/vaultwarden/vaultwarden-nginx.nix

    map $http_upgrade $connection_upgrade {
      # ** Set the default value for the connection upgrade header to "upgrade", which is required for WebSocket connections.
      # ** It's an optional directive that specifies the default value for the connection upgrade header if it is not set in the request. This is useful for WebSocket connections, which require the connection upgrade header to be set to "upgrade". By setting the default value to "upgrade", we ensure that WebSocket connections will work even if the client does not set the connection upgrade header.
      default upgrade;
      ""      close;
    }

    # ---- HTTPS ONLY
    # This vhost deliberately declares no port 80 server block, so nothing
    # here listens on plain HTTP and no HTTP -> HTTPS redirect exists.

    # ------------------------------------------------------------
    # HTTPS REVERSE PROXY
    # ------------------------------------------------------------
    server {
      # Listen on port 443 for both IPv4 and IPv6 with SSL enabled
      listen 443 ssl;
      listen [::]:443 ssl;
      server_name ${serverNames};

      # Use the mkcert-generated certificate and key for SSL
      ssl_certificate ${certPem};
      ssl_certificate_key ${keyPem};

      # Set SSL session parameters for better performance and security
      ssl_session_timeout 1d;

      # Set the SSL session cache to shared memory with a size of 10MB
      ssl_session_cache shared:SSL:10m;

      # Disable SSL session tickets for improved security
      ssl_session_tickets off;

      # Set the preferred SSL protocols to TLSv1.2 and TLSv1.3 for better security
      ssl_protocols TLSv1.2 TLSv1.3;

      # Set the preferred cipher suites for TLSv1.2 and TLSv1.3
      ssl_prefer_server_ciphers off;

      # Set the maximum allowed size of the client request body to 128MB
      client_max_body_size 128M;

      # ----------------------------------------------------------
      # MAIN VAULTWARDEN APP
      # ----------------------------------------------------------
      location / {
      	# Proxy requests to the Vaultwarden backend
        proxy_pass http://127.0.0.1:${toString hostPort};

        # ---- SET HEADERS FOR WEBSOCKET SUPPORT

        # Set the Host header to the original host requested by the client
        proxy_set_header Host $host;

        # Set the X-Real-IP header to the original client IP address
        proxy_set_header X-Real-IP $remote_addr;

        # Set the X-Forwarded-For header to include the original client IP address
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Set the X-Forwarded-Proto header to indicate the original protocol (HTTP or HTTPS)
        proxy_set_header X-Forwarded-Proto $scheme;

        # Use HTTP/1.1 for WebSocket connections
        proxy_http_version 1.1;

        # Set the Upgrade and Connection headers to support WebSocket connections
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
      }

      # ----------------------------------------------------------
      # WEBSOCKET ENDPOINT
      # ----------------------------------------------------------
      location /notifications/hub {
        proxy_pass http://127.0.0.1:${toString hostPort};

        # ---- SET HEADERS FOR WEBSOCKET SUPPORT

        # Set the Host header to the original host requested by the client
        proxy_set_header Host $host;

        # Set the X-Real-IP header to the original client IP address
        proxy_set_header X-Real-IP $remote_addr;

        # Set the X-Forwarded-For header to include the original client IP
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Set the X-Forwarded-Proto header to indicate the original protocol (HTTP or HTTPS)
        proxy_set_header X-Forwarded-Proto $scheme;

        # Use HTTP/1.1 for WebSocket connections
        proxy_http_version 1.1;

        # Set the Upgrade and Connection headers to support WebSocket connections
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection $connection_upgrade;
      }

      # Use the same proxy settings for the negotiate endpoint
      location /notifications/hub/negotiate {
        proxy_pass http://127.0.0.1:${toString hostPort};

        # Set headers for WebSocket support
        proxy_set_header Host $host;

        # Set headers for WebSocket support
        proxy_set_header X-Real-IP $remote_addr;

        # Set the X-Forwarded-For header to include the original client IP
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

        # Set the X-Forwarded-Proto header to indicate the original protocol (HTTP or HTTPS)
        proxy_set_header X-Forwarded-Proto $scheme;

        # Use HTTP/1.1 for WebSocket connections
        proxy_http_version 1.1;
      }
    }
  '';
in
{
  # Register the vhost. nginx.nix adds the matching include line and
  # writes /etc/nginx/apps-enabled/vaultwarden.conf.
  #
  # ** The certificate is no longer checked here. nginx.nix runs 'nginx -t'
  # ** before every start and before every reload, and that fails on a
  # ** missing cert or key anyway, so a second check would only duplicate it.
  # When ven.nginx is disabled this definition is simply never consumed.
  ven.nginx.virtualHosts.${appName} = generatedConf;
}
